refactor: Clean after code review
epam/badgerdoc pull request #362
Opened 2023-02-22 12:35 UTC by serereg

Clean after code review.

Relates to https://github.com/epam/badgerdoc/issues/66
Relates to https://github.com/epam/badgerdoc/issues/170

2023-02-27 10:15 UTC, cakeinsauce requested changes
Few more things:
- You don't need to add empty `__init__.py` in every folder. Python has namespace packages
- Let's make a package called `formats` which contains subpackages with different convert models. And remove format word from anywhere here, please. E.g. `formats` [package]  -> `badgerdoc` [package] -> `class Badgerdoc`

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_import_text.py
> +    monkeypatch.setattr(TextToBadgerdocConverter, "upload", mock_upload_text)
Up to you

```suggestion
    monkeypatch.setattr(
        TextToBadgerdocConverter, "download", lambda *args, **kw: "1"
    )
    monkeypatch.setattr(TextToBadgerdocConverter, "upload",  lambda *args, **kw: pass)
```

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_import_labelstudio.py
> +    )
Up to you
```suggestion
    monkeypatch.setattr(
        LabelstudioToBadgerdocConverter,
        "download",
        lambda *args, **kw: LabelStudioModel(),
    )
    monkeypatch.setattr(
        LabelstudioToBadgerdocConverter,
        "upload",
        lambda *args, **kw: pass,
    )
    monkeypatch.setattr(
        LabelstudioToBadgerdocConverter, "execute", lambda *args, **kw: pass
    )
```

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_export_labelstudio.py
> +    )
Up to you
```suggestion
    monkeypatch.setattr(
        BadgerdocToLabelstudioConverter, "execute", lambda *args, **kw: pass
    )
```

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/conftest.py
> +    yield client
```suggestion
    yield TestClient(main.app)
```

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/conftest.py
> +    return mock_tenant_data
```suggestion
    return TenantData(
        token="token",
        user_id="owner1",
        roles=["admin"],
        tenants=["tenant", "test"],
    )
```

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_export_labelstudio.py
> +def test_correctness_of_export_text_schema(test_app, monkeypatch):
Add typings, please

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_export_labelstudio.py
> +def test_annotation_converter_case_without_taxonomies_and_document_labels():
Add typings, please

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_import_labelstudio.py
> +def test_correctness_of_import_text_schema(test_app, monkeypatch):
Add typings, please

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_import_labelstudio.py
>  def test_plain_text_converter():
Add typings, please

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_import_labelstudio.py
>  def test_import_document_links():
Add typings, please

2023-02-27 10:15 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_import_text.py
> +def test_correctness_of_import_text_schema(test_app, monkeypatch):
Add typings, please

2023-02-27 10:15 UTC, cakeinsauce commented on convert/src/plain_text_format/plain_text_converter.py
> +    def convert_line(self, line, tokens, y_axis, line_offset: int):
Add typings, please

2023-02-27 10:15 UTC, cakeinsauce commented on convert/src/plain_text_format/plain_text_converter.py
> +        tokens: List[BadgerdocToken], page_border_offset
Add typings, please

2023-02-28 16:52 UTC, cakeinsauce commented on convert/src/text_to_badgerdoc_converter.py
> +            s3_output_tokens: S3Path,
Remove redundant tab please

2023-02-28 16:52 UTC, cakeinsauce commented on convert/src/badgerdoc_to_labelstudio_converter.py
>      ):
add typing, please

2023-03-01 04:41 UTC, serereg commented on convert/tests/test_labelstudio/test_import_text.py
> +def test_correctness_of_import_text_schema(test_app, monkeypatch):
Done

2023-03-01 04:41 UTC, serereg commented on convert/tests/test_labelstudio/conftest.py
> +def test_app(setup_tenant):
Done

2023-03-01 04:42 UTC, serereg commented on convert/tests/test_labelstudio/conftest.py
> +def setup_tenant():
Done

2023-03-01 04:42 UTC, serereg commented on convert/src/text_to_badgerdoc_converter.py
>          s3_client,
Done

2023-03-01 04:43 UTC, serereg commented on convert/src/plain_text_format/plain_text_converter.py
> +    def convert_line(self, line, tokens, y_axis, line_offset: int):
Done

2023-03-01 04:43 UTC, serereg commented on convert/src/text_to_badgerdoc_converter.py
> +            s3_output_tokens: S3Path,
Done

2023-03-01 04:44 UTC, serereg commented on convert/src/badgerdoc_to_labelstudio_converter.py
>      ):
Done

2023-03-01 04:45 UTC, serereg commented on convert/tests/test_labelstudio/test_import_labelstudio.py
> +def test_correctness_of_import_text_schema(test_app, monkeypatch):
Done

2023-03-01 04:45 UTC, serereg commented on convert/tests/test_labelstudio/test_export_labelstudio.py
> +def test_correctness_of_export_text_schema(test_app, monkeypatch):
Done

2023-03-01 10:44 UTC, cakeinsauce commented on convert/tests/test_labelstudio/test_import_labelstudio.py
> +def test_correctness_of_import_text_schema(test_app, monkeypatch):
Return typing as well, please

2023-03-01 11:13 UTC, serereg commented on convert/tests/test_labelstudio/test_import_labelstudio.py
> +def test_correctness_of_import_text_schema(test_app, monkeypatch):
Done

2023-03-01 11:22 UTC, cakeinsauce approved these changes
LGTM!
Squash commits before merging, please
And don't forget about repos' commits convention

2023-03-01 11:29 UTC, merged