Remove non-printing tokens during labelstudio import and export
epam/badgerdoc pull request #398
Opened 2023-03-01 20:42 UTC by serereg

https://github.com/epam/badgerdoc/issues/264

2023-03-02 08:33 UTC, AnastasiiaPlyako approved these changes

2023-03-02 12:22 UTC, spiridonovfed requested changes

2023-03-02 12:22 UTC, spiridonovfed commented on convert/src/converters/utils.py
> +            )
I would rewirte this way:
![image](https://user-images.githubusercontent.com/76848937/222427393-84d16752-207f-42ce-9983-19d4e9dceb9c.png)

2023-03-03 06:32 UTC, spiridonovfed approved these changes

2023-03-03 06:36 UTC, merged