Remove not needed parts from Readme
epam/badgerdoc pull request #481
Opened 2023-03-28 07:58 UTC by nanbratan

2023-03-28 08:28 UTC, Iogsotot approved these changes

2023-03-28 09:13 UTC, Iogsotot commented on web/README.md
> +cd badgerdoc
![image](https://user-images.githubusercontent.com/50149163/228188412-406fbaf1-bbc0-493f-8d57-40523de12d01.png)
I guess you forgot about the `web` subfolder

2023-03-28 09:19 UTC, Iogsotot commented on web/README.md
> +To learn React, check out the [React documentation](https://reactjs.org/).
new link for v17 - [legacy.reactjs.org](https://legacy.reactjs.org/docs/hello-world.html)
for v18+ - [react.dev](https://react.dev/)

2023-03-28 09:22 UTC, Iogsotot commented
It seems to me that it would be great to add a description of the code style (or a link to it), instructions for writing and running tests, their description

2023-03-28 11:34 UTC, nanbratan commented on web/README.md
> +To learn about UII, visit [UUI documentation website](https://uui.epam.com/).\
They are line-breaks

2023-04-01 21:38 UTC, cakeinsauce requested changes
Adjust commit message before merging, please
https://github.com/epam/badgerdoc/blob/main/CONTRIBUTING.md

2023-04-08 04:14 UTC, khyurri approved these changes

2023-04-08 04:17 UTC, khyurri commented
> Adjust commit message before merging, please https://github.com/epam/badgerdoc/blob/main/CONTRIBUTING.md

Let's automate this checks in https://github.com/epam/badgerdoc/issues/7

2023-04-28 08:59 UTC, closed without merging