async(annotation): jobs_communication
epam/badgerdoc pull request #941
Opened 2024-08-27 08:44 UTC by Negoje

2024-08-27 17:03 UTC, BogicevicMilan commented on annotation/annotation/microservice_communication/jobs_communication.py
> +# def update_job_status_sync(
Please remove this if you don't plan to use it in the future.

2024-08-27 17:29 UTC, BogicevicMilan commented on annotation/annotation/microservice_communication/jobs_communication.py
> +# def append_job_categories_sync(
same comment

2024-08-27 20:54 UTC, Negoje commented on annotation/tests/test_microservices_jobs_communication.py
> +            await update_job_status(callback_url, status, tenant, token)
You should be able to install pytest-asyncio now and all test should work

2024-08-28 08:26 UTC, UkiStefanovic approved these changes
Looks good

2024-08-28 14:46 UTC, cakeinsauce requested changes

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/annotation/microservice_communication/jobs_communication.py
> +                    raise JobUpdateException(text)
```suggestion
                    raise JobUpdateException(await response.text())
```

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/annotation/microservice_communication/jobs_communication.py
> +                    raise JobUpdateException(text)
```suggestion
                    raise JobUpdateException(await response.text())
```

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/pyproject.toml
> +pytest = "^8.2"
pytest is not a project dependency, it is dev only

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/pyproject.toml
> +pytest = "^8.2"
remove it and update lock file, please

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/tests/test_distribution.py
> +@pytest.mark.asyncio
Remove this decorator from all tests and add configuration to pyproject.toml for pytest to automatically include it
https://pytest-asyncio.readthedocs.io/en/latest/reference/configuration.html

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/tests/test_microservices_jobs_communication.py
> +async def test_append_job_categories_success(setup_append_job_categories):
typing, please

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/tests/test_microservices_jobs_communication.py
> +
```suggestion
```

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/tests/test_microservices_jobs_communication.py
> +    setup_append_job_categories,
typing, please

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/tests/test_microservices_jobs_communication.py
> +async def test_append_job_categories_client_error(setup_append_job_categories):
typing, please

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/tests/test_microservices_jobs_communication.py
> +async def test_update_job_status_success(job_status_setup):
typing, please

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/tests/test_microservices_jobs_communication.py
> +async def test_update_job_status_failure_non_200(job_status_setup):
typing, please

2024-08-28 14:46 UTC, cakeinsauce commented on annotation/tests/test_microservices_jobs_communication.py
> +async def test_update_job_status_client_error(job_status_setup):
typing, please

2024-08-29 12:19 UTC, cakeinsauce commented on annotation/pytest.ini
> +asyncio_mode = auto
add new line, please

2024-08-30 10:25 UTC, cakeinsauce approved these changes
Great, test it in fully working env, please

2024-08-30 13:07 UTC, merged